// Copyright 2012 Philippe Quesnel
// Licensed under the Academic Free License version 3.0

// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef mainWndFl_h
#define mainWndFl_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>

class MainWindowFl {
public:
  MainWindowFl();
protected:
  Fl_Double_Window *window;
public:
  Fl_Choice *rootDestChoice;
  Fl_Input *subdirInput;
  Fl_Input *localRootInput;
  Fl_Browser *filesBrowser;
  virtual ~MainWindowFl();
  virtual void show(int argc, char ** argv);
  virtual void hide();
};
#endif
