// AndroidPush project
// Copyright 2012 Philippe Quesnel
// Licensed under the Academic Free License version 3.0

/*   Automatically generated by Iup 3 LED Compiler to C.   */

import iup.iup;
import iup.utild;


// just alias _IupSetAtt to IupSetAtt '-)
alias _IupSetAtt IupSetAtt;

Ihandle* named[      7 ];

void led_load ()
{
  named[0] = IupSetAtt( "mainDialog", IupDialog(
    IupSetAtt( NULL, IupVbox(
      IupSetAtt( NULL, IupFrame(
        IupSetAtt( NULL, IupVbox(
          named[1] = IupSetAtt( "localRoot", IupText( "do_nothing" ),
            "EXPAND", "HORIZONTAL",
            "MARGIN", "5", NULL ),
        NULL),
          "NMARGIN", "5x2",
          "EXPAND", "HORIZONTAL", NULL )
      ),
        "TITLE", "Local Root", NULL ),
      IupSetAtt( NULL, IupFrame(
        IupSetAtt( NULL, IupVbox(
          IupVbox(
            IupLabel( "Root" ),
            named[2] = IupSetAtt( "destinationRoot", IupList( "do_nothing" ),
              "1", "aa",
              "2", "bb",
              "3", "cc",
              "DROPDOWN", "YES",
              "EXPAND", "HORIZONTAL", NULL ),
          NULL),
          IupSetAtt( NULL, IupFill(),
            "SIZE", "4", NULL ),
          IupVbox(
            IupLabel( "Files" ),
            named[3] = IupSetAtt( "files", IupList( "do_nothing" ),
              "EXPAND", "YES", NULL ),
          NULL),
        NULL),
          "NMARGIN", "5x5",
          "EXPAND", "YES", NULL )
      ),
        "TITLE", "Destination", NULL ),
      IupSetAtt( NULL, IupHbox(
        IupFill(),
        named[4] = IupSetAtt( "pushButton", IupButton( "Push", "onPushButton" ),
          "PADDING", "4x1", NULL ),
      NULL),
        "EXPAND", "HORIZONTAL",
        "MARGIN", "5x2", NULL ),
    NULL),
      "NMARGIN", "5x5",
      "NGAP", "5x5",
      "EXPAND", "YES", NULL )
  ),
    "TITLE", "Android Push",
    "MINSIZE", "300x300", NULL );

}
