// main.d, test using IUP in D (with LED file)

// Copyright 2012 Philippe Quesnel
// Licensed under the Academic Free License version 3.0

module main;

import std.stdio;
import std.string;
import std.utf;
import std.exception;
import std.conv;
import std.typecons;

import iup.iup;
import iup.controls;
import iup.utild;
import iup.widget;



class MainWindow : IupWidget {

    this() {
//        super("mainDialog");
        led_load();
        super(named[0]);
    }




/*   Automatically generated by Iup 3 LED Compiler to C.   */
// just change IupSetAtt to _IupSetAtt '-)
Ihandle* named[      6 ];
void led_load ()
{
  named[0] = _IupSetAtt( "mainDialog", IupDialog(
    _IupSetAtt( NULL, IupVbox(
      _IupSetAtt( NULL, IupFrame(
        _IupSetAtt( NULL, IupVbox(
          named[1] = _IupSetAtt( "localRoot", IupText( "NULL" ),
            "EXPAND", "HORIZONTAL",
            "MARGIN", "5", NULL ),
        NULL),
          "NMARGIN", "5x5",
          "NGAP", "5x5",
          "EXPAND", "YES", NULL )
      ),
        "TITLE", "Local Root", NULL ),
      _IupSetAtt( NULL, IupFrame(
        _IupSetAtt( NULL, IupVbox(
          IupVbox(
            IupLabel( "Root" ),
            named[2] = _IupSetAtt( "destinationRoot", IupList( "NULL" ),
              "1", "aa",
              "2", "bb",
              "3", "cc",
              "DROPDOWN", "YES",
              "EXPAND", "HORIZONTAL", NULL ),
          NULL),
          IupVbox(
            IupLabel( "Files" ),
            named[3] = _IupSetAtt( "files", IupList( "null" ),
              "EXPAND", "YES", NULL ),
          NULL),
        NULL),
          "NMARGIN", "5x5",
          "NGAP", "5x5",
          "EXPAND", "YES", NULL )
      ),
        "TITLE", "Destination", NULL ),
      _IupSetAtt( NULL, IupHbox(
        IupFill(),
        named[4] = _IupSetAtt( "pushButton", IupButton( "Push", "onPushButton" ), NULL ),
      NULL),
        "EXPAND", "HORIZONTAL",
        "SIZE", "150", NULL ),
    NULL),
      "NMARGIN", "5x5",
      "NGAP", "5x5",
      "EXPAND", "YES", NULL )
  ),
    "TITLE", "Android Push",
    "MARGINS", "5x5", NULL );
}

    // button event callback
    int button2Cb(Ihandle* ihandle) {
        return IUP_DEFAULT;
    }

    void run() {

        /* shows dialog */
        this.Show();

        /* main loop */
        IupMainLoop();
    }
}

//---------------------

int main(string[] args)
{

    try {
        /* IUP initialization */
        IupOpenD(args);
        IupControlsOpen() ;

        /* loads LED 'resource' file */
        char* error = IupLoad("androidGUI.led");
        enforce(!error, to!string(error));

        scope auto window = new MainWindow;
        window.run();

    }
    catch (Exception e) {
        IupMessage("error", e.msg.toStringz);
    }
    finally {
        /* ends IUP */
        IupControlsClose();
        IupClose();
    }

	return 0;
}
